id: A197D9417
title: Daily Confession (from the Vajrapañjara Tantra)
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:02:16.871930
  last_modified_at: 2022-03-01 06:02:16.871937
