id: A197D9417
title: The Outer, Inner and Secret Refuge Prayer
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:02:16.878452
  last_modified_at: 2022-03-01 06:02:16.878458
