id: A197D9417
title: Verses of Refuge and Bodhicitta
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:02:16.881001
  last_modified_at: 2022-03-01 06:02:16.881008
